force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <label>Breed</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Beagle</fullName>
            </value>
            <value>
                <fullName>Bulldog</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Dachshund</fullName>
            </value>
            <value>
                <fullName>German Shepherd</fullName>
            </value>
            <value>
                <fullName>Golden Retriever</fullName>
            </value>
            <value>
                <fullName>Labrador Retriever</fullName>
            </value>
            <value>
                <fullName>Poodle</fullName>
            </value>
            <value>
                <fullName>Rottweiler</fullName>
            </value>
            <value>
                <fullName>Siberian Husky</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Photo_Link__c.field-meta.xml
<CustomField>
    <fullName>Photo_Link__c</fullName>
    <label>Photo Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shelter</label>
    <referenceTo>Shelter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals_Shelters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Animal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
            <value>
                <fullName>Under medical treatment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Shelters</relationshipLabel>
    <relationshipName>Shelters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AnimalFinderController.cls
public with sharing class AnimalFinderController {

    @AuraEnabled(cacheable=true)
    public static List<Animal__c> getAnimals(String shelterId, String breed, String ageRange, String sex) {
        String query = 'SELECT Id, Name, Breed__c, Age__c, Sex__c, Photo_Link__c,' +
                       'Shelter__c, Shelter__r.Name ' +
                       'FROM Animal__c ' +
                       'WHERE Status__c = \'Available\'';
        
        if (String.isNotBlank(shelterId)) {
            query += ' AND Shelter__c = :shelterId';
        }

        if (String.isNotBlank(breed)) {
            query += ' AND Breed__c = :breed';
        }
        
        if (String.isNotBlank(ageRange)) {
            switch on ageRange {
                when '0-2' {
                    query += ' AND Age__c <= 2';
                }
                when '3-5' {
                    query += ' AND Age__c >= 3 AND Age__c <= 5';
                }
                when '6-10' {
                    query += ' AND Age__c >= 6 AND Age__c <= 10';
                }
                when '10+' {
                    query += ' AND Age__c > 10';
                }
            }
        }

        if (String.isNotBlank(sex)) {
            query += ' AND Sex__c = :sex';
        }
        
        query += ' ORDER BY Name';
        
        return Database.query(query);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Shelter__c> getShelters() {
        return [SELECT Id, Name FROM Shelter__c 
                ORDER BY Name];
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getBreeds() {
        List<String> breeds = new List<String>();

        List<Schema.PicklistEntry> entries = Animal__c.Breed__c.getDescribe().getPickListValues();
        for (Schema.PicklistEntry entry : entries) {
            breeds.add(entry.getValue());
        }
        return breeds;
    }
}