force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shelter</label>
    <referenceTo>Shelter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals_Shelters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Shelters</relationshipLabel>
    <relationshipName>Shelters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/UnadoptedAnimals__c.field-meta.xml
<CustomField>
    <fullName>UnadoptedAnimals__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UnadoptedAnimals</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnimalTriggerHandler.cls
public with sharing class AnimalTriggerHandler extends TriggerHandler{
     public override void afterInsert(List<SObject> newList) {
        List<Animal__c> animals = (List<Animal__c>) newList;
        addingMissingAnimals(animals);
        
    }

    public static void addingMissingAnimals(List<Animal__c> animals) {

        Set<Id> shelterIds = new Set<Id>();
        for (Animal__c a : animals) {
            if (a.Shelter__c != null) {
                shelterIds.add(a.Shelter__c);
            }
        }

        Map<Id, Shelter__c> shelterMap = new Map<Id, Shelter__c>(
            [SELECT Id, UnadoptedAnimals__c FROM Shelter__c WHERE Id IN :shelterIds]
        );

        Map<Id, double> countMap = new Map<Id, double>();
        for (Animal__c a : animals) {
            if (a.Shelter__c != null) {
                if (!countMap.containsKey(a.Shelter__c)) {
                    countMap.put(a.Shelter__c, 0);
                }
                countMap.put(a.Shelter__c, countMap.get(a.Shelter__c) + 1);
            }
        }

        List<Shelter__c> sheltersToUpdate = new List<Shelter__c>();
        for (Id shelterId : countMap.keySet()) {
            Shelter__c s = shelterMap.get(shelterId);
            double currentCount = (s.UnadoptedAnimals__c == null) ? 0 : s.UnadoptedAnimals__c;
            s.UnadoptedAnimals__c = currentCount + countMap.get(shelterId);
            sheltersToUpdate.add(s);
        }

        update sheltersToUpdate;
    }
}