force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <label>Adoption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions_Animal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Animal__c/Animal__c.object-meta.xml
<CustomObject>
    <label>Animal</label>
    <nameField>
        <label>Animal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Animals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Animal__c/fields/Shelter__c.field-meta.xml
<CustomField>
    <fullName>Shelter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shelter</label>
    <referenceTo>Shelter__c</referenceTo>
    <relationshipLabel>Animals</relationshipLabel>
    <relationshipName>Animals_Shelters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <referenceTo>Animal__c</referenceTo>
    <relationshipLabel>Shelters</relationshipLabel>
    <relationshipName>Shelters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shelter__c/fields/Number_Of_Adoptions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Adoptions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Adoptions</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CountigAdoptionHandler.cls
public class CountigAdoptionHandler {
	
    public static void updateAdoptions(List<Adoption__c> Adoptions){
        
        Set<Id> animalsId = new Set<Id>();
        
        for(Adoption__c a : Adoptions){
            animalsId.add(a.Animal__c);
            
        }
        
        List<Animal__c> animals = new List<Animal__c>();
        
        animals = [Select Id, Shelter__c from Animal__c where Animal__c.Id in : animalsId];
        
        Map<Id, Id> shelterMap = new Map<Id, Id>();

        for(Animal__c a : animals){
        	shelterMap.put(a.Id, a.Shelter__c);    
        }
        
        Set<Id> shelterIds = new Set<Id>();

        for(Adoption__c a : Adoptions){
            Id animalId = a.Animal__c;
            if(shelterMap.containsKey(animalId)){
                shelterIds.add(shelterMap.get(animalId));
            }
        }
        
        Map<Id, Integer> shelterAdoptionCounts = new Map<Id, Integer>();

        for(Adoption__c a : Adoptions){
            Id shelterId = shelterMap.get(a.Animal__c);
            if(shelterId != null){
                if(!shelterAdoptionCounts.containsKey(shelterId)){
                    shelterAdoptionCounts.put(shelterId, 1);
                } else {
                    shelterAdoptionCounts.put(shelterId, shelterAdoptionCounts.get(shelterId) + 1);
                }
            }
        }
        
        List<Shelter__c> sheltersToUpdate = new List<Shelter__c>();

        for(Id shelterId : shelterAdoptionCounts.keySet()){
            Shelter__c Shelter = new Shelter__c(Id = shelterId, Number_of_Adoptions__c = shelterAdoptionCounts.get(shelterId));
            sheltersToUpdate.add(Shelter);
		}
        
       update sheltersToUpdate; 
    }
    
}