force-app/main/default/objects/Account/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Adoption__c/Adoption__c.object-meta.xml
<CustomObject>
    <label>Adoption</label>
    <nameField>
        <label>Adoption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adoptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Adoption__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adoptions</relationshipLabel>
    <relationshipName>Adoptions_Account</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Adoption__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;In progress&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CountingPoints.cls
public with sharing class CountingPoints{
    public static void updatePoints(List<Adoption__c> Adoptions){
    Id realId = Schema.SObjectType.Adoption__c.getRecordTypeInfosByName().get('Real').getRecordTypeId();
    
    List<Account> accsToUpdate = new List<Account>();
    List<Account> accounts = new List<Account>();
    Map<Id, Integer> pointsToAdd = new Map<id, Integer>();

    for(Adoption__c adopt : Adoptions){
        if(adopt.Status__c == 'Approved'){
        Id accountId = adopt.Account__c;
        Integer newPoints = (adopt.RecordTypeId == realId) ? 20 : 10;
        Integer currPoints = pointsToAdd.get(accountId) ?? 0;
        pointsToAdd.put(accountId, currPoints + newPoints);
        }
    }
    
    accounts = [SELECT Id, Points__c FROM Account WHERE Id IN :pointsToAdd.keySet()];

    for (Account acc : accounts) {
        Integer pointsToAddNow = pointsToAdd.get(acc.Id);
        acc.Points__c = (acc.Points__c ?? 0) + pointsToAddNow;
        accsToUpdate.add(acc);
    }
    update accsToUpdate;
    }
}